services:
  prometheus:
    container_name: milvus-prometheus
    image: prom/prometheus:latest
    network_mode: host
    command:
      - "--config.file=/etc/prometheus/prometheus.yml --web.enable-admin-api"
    stdin_open: true
    tty: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      
  alertmanger:
    container_name: milvus-alertmanager
    image: quay.io/prometheus/alertmanager:latest
    ports:
      - "9093:9093"

  grafana:
    container_name: milvus-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard.json:/var/lib/grafana/dashboards/milvus.json
      
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    ports:
      - "2379:2379"
    volumes:
      - /var/lib/milvus/etcd:/etcd
      # - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - /var/lib/milvus/minio:/minio_data
      # - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # standalone:
  #   container_name: milvus-standalone
  #   # build:
  #   #   context: .
  #   #   tags:
  #   #     - "neokkk/milvus-standalone:0.1"
  #   image: "neokkk/milvus-standalone:0.1"
  #   command: ["/milvus/bin/milvus-docker", "run", "standalone"]
  #   security_opt:
  #     - seccomp:unconfined
  #   environment:
  #     ETCD_ENDPOINTS: etcd:2379
  #     MINIO_ADDRESS: minio:9000
  #     LD_LIBRARY_PATH: /milvus/lib:${LD_LIBRARY_PATH:-/usr/lib}
  #   volumes:
  #     - ${HOME}/milvus/bin/:/milvus/bin/
  #     - ${HOME}/milvus/internal/core/output/lib:/milvus/lib/
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
  #     interval: 30s
  #     start_period: 90s
  #     timeout: 20s
  #     retries: 3
  #   ports:
  #     - "9091:9091"
  #     - "19530:19530"
  #   depends_on:
  #     - "etcd"
  #     - "minio"

networks:
  default:
    name: milvus
